[package]
name = "omapix"
version.workspace = true
edition.workspace = true
license.workspace = true

[dev-dependencies]
pollster = "1.0.1"

[dependencies]
bytemuck = "1.25.2"
eframe = { version = "0.36.2", default-features = false, features = ["wgpu", "wayland", "x11", "default_fonts"] }
egui = "0.36.2"
env_logger = "0.11.11"
log = "0.4.34"
omapix-engine = { version = "0.1.0", path = "../omapix-engine" }
rayon = "1.12.0"
rfd = "0.17.2"
smithay-clipboard = "0.7.3"
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"
